# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{konto_check}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Provideal Systems GmbH", "Jan Schwenzien", "Michael Plugge"]
  s.date = %q{2011-08-05}
  s.description = %q{Check whether a certain bic/account-no-combination or an IBAN can possibly be valid, retrieve informations about a bank or search for BICs matching certain criteria. It uses the C library kontocheck (see http://sourceforge.net/projects/kontocheck/) by Michael Plugge.}
  s.email = %q{info@provideal.net}
  s.extensions = ["ext/konto_check_raw/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile",
    "ext/konto_check_raw/konto_check_raw_ruby.c"
  ]
  s.files = [
    "CHANGES",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION.yml",
    "ext/konto_check_raw/extconf.rb",
    "ext/konto_check_raw/konto_check.c",
    "ext/konto_check_raw/konto_check.h",
    "ext/konto_check_raw/konto_check_raw_ruby.c",
    "init.rb",
    "konto_check.gemspec",
    "lib/konto_check.rb",
    "test/helper.rb",
    "test/test_konto_check.rb"
  ]
  s.homepage = %q{http://github.com/provideal/konto_check}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Checking german BICs/Bank account numbers and IBANs, retrieve information about german Banks, search for Banks matching certain criteria}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

